name: Build and Test ShoMeDaMoney

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ShoMeDaMoney.sln

    - name: Build
      run: dotnet build ShoMeDaMoney.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ShoMeDaMoney.sln --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish ShoMeDaMoney.sln --configuration Release --no-build --output ./out

    - name: Zip package
      run: |
        cd out
        zip -r ../ShoMeDaMoney.zip .
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ShoMeDaMoneyPackage
        path: ShoMeDaMoney.zip
        
  iac:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy IaC
      run: az deployment group create --resource-group shomedamoney --template-file iac/prod.bicep